---
- name: Pre-provisioning for black box
  hosts: all
  sudo: yes
  roles:
    - base
    - vagrant
    - apache
    - sources
    - git
    - ohmyzsh
    - postfix
    - mariadb
    - mongo
    - dotdeb
    - composer
    - clean