---
- name: Add key to vagrant user
  user: >
    state=present
    name=vagrant
    comment="Vagrant User"
    shell=/bin/bash
    home=/home/vagrant
    createhome=yes
    password={{ vagrant_password }}

- name: Change permissions for ssh directory
  file: path=/home/vagrant/.ssh owner=vagrant group=vagrant mode=0700 state=directory
  tags: install

- name: Install vagrant key
  get_url: >
    url=https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub
    dest=/home/vagrant/.ssh/authorized_keys
    owner=vagrant
    group=vagrant
    mode=0600
    sha256sum=9aa9292172c915821e29bcbf5ff42d4940f59d6a148153c76ad638f5f4c6cd8b
  tags: install

- name: Install sudo (Debian only)
  apt: pkg=sudo state=present
  when: ansible_distribution == 'Debian'

- name: Add vagrant to sudoers
  lineinfile: >
    state=present
    dest=/etc/sudoers.d/vagrant
    create=yes
    regexp="vagrant"
    mode=0440
    line='vagrant ALL=NOPASSWD:ALL'
  tags: install