---
- name: Install deps
  apt: name={{ item }} state=present
  with_items:
    - libcurl4-gnutls-dev
    - gettext
  tags: git

- name: Get last stable version
  get_url: url=https://github.com/git/git/archive/v2.2.0.tar.gz dest=/tmp/v2.2.0.tar.gz
  tags: git

- name: Extract last stable version
  command: tar -xvzf /tmp/v2.2.0.tar.gz chdir=/tmp/ creates=/tmp/git-2.2.0/README warn=true
  tags: git

- name: Install last stable version
  command: make prefix=/usr/local all chdir=/tmp/git-2.2.0
  tags: git

- name: Install last stable version (2)
  command: make prefix=/usr/local install chdir=/tmp/git-2.2.0
  tags: git

- name: Copy default gitconfig
  template: src=gitconfig.j2 dest=/etc/gitconfig
  tags: git