---
- name: Install deps
  apt: name={{ item }} state=present
  with_items:
    - libcurl4-gnutls-dev
    - gettext
  tags: git

- name: Get last stable version
  get_url: url=https://github.com/git/git/archive/v2.1.3.tar.gz dest=/tmp/
  tags: git

- name: Extract last stable version
  unarchive: src=/tmp/v2.1.3.tar.gz dest=/tmp/v2.1.3
  tags: git

- name: Install last stable version
  shell: cd /tmp/v2.1.3/ && make prefix=/usr/local all && make prefix=/usr/local install && cd ~
  tags: git

- name: Ignorecase
  shell: git config --unset-all core.ignorecase && git config --system core.ignorecase false
  tags: git

- name: Copy default gitconfig
  template: src=gitconfig.j2 dest=/etc/gitconfig
  tags: git